# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: control.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'control.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcontrol.proto\x12\x0c\x63leo.control\"E\n\x0f\x44\x65\x63isionRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\r\n\x05state\x18\x03 \x01(\x0c\"=\n\x10\x44\x65\x63isionResponse\x12)\n\toperators\x18\x01 \x03(\x0b\x32\x16.cleo.control.Operator\"<\n\x08Operator\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0f\n\x07utility\x18\x03 \x01(\x02\"4\n\rActionRequest\x12\x13\n\x0boperator_id\x18\x01 \x01(\t\x12\x0e\n\x06params\x18\x02 \x01(\x0c\"(\n\tActionAck\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xab\x01\n\x0e\x43ontrolService\x12R\n\x0fRequestDecision\x12\x1d.cleo.control.DecisionRequest\x1a\x1e.cleo.control.DecisionResponse\"\x00\x12\x45\n\x0b\x41pplyAction\x12\x1b.cleo.control.ActionRequest\x1a\x17.cleo.control.ActionAck\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'control_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DECISIONREQUEST']._serialized_start=31
  _globals['_DECISIONREQUEST']._serialized_end=100
  _globals['_DECISIONRESPONSE']._serialized_start=102
  _globals['_DECISIONRESPONSE']._serialized_end=163
  _globals['_OPERATOR']._serialized_start=165
  _globals['_OPERATOR']._serialized_end=225
  _globals['_ACTIONREQUEST']._serialized_start=227
  _globals['_ACTIONREQUEST']._serialized_end=279
  _globals['_ACTIONACK']._serialized_start=281
  _globals['_ACTIONACK']._serialized_end=321
  _globals['_CONTROLSERVICE']._serialized_start=324
  _globals['_CONTROLSERVICE']._serialized_end=495
# @@protoc_insertion_point(module_scope)