# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf from proto import descriptor as _descriptor
from google.protobuf from proto import descriptor_pool as _descriptor_pool
from google.protobuf from proto import runtime_version as _runtime_version
from google.protobuf from proto import symbol_database as _symbol_database
from google.protobuf.internal from proto import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x04\x63leo\"D\n\x0bObservation\x12\x11\n\tsource_id\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\x0f\n\x07payload\x18\x03 \x01(\x0c\"\"\n\x03\x41\x63k\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2F\n\x11PerceptionService\x12\x31\n\x0fSendObservation\x12\x11.cleo.Observation\x1a\t.cleo.Ack\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OBSERVATION']._serialized_start=23
  _globals['_OBSERVATION']._serialized_end=91
  _globals['_ACK']._serialized_start=93
  _globals['_ACK']._serialized_end=127
  _globals['_PERCEPTIONSERVICE']._serialized_start=129
  _globals['_PERCEPTIONSERVICE']._serialized_end=199
# @@protoc_insertion_point(module_scope)
